// Chart geometry — the numbers every Register P chart is drawn with, computed once.
//
// This module is geometry ONLY: path `d` strings, dash values, viewBoxes and the positions of the
// labels a surface then fills in its own language. No colour, no copy — a tone is a name a client
// maps onto the S1 tokens, and a string position is where a translated label sits.
//
// Every pinned number below is what the boards draw (`product/design/pro` on ieat-app main
// d3fe6ef8, generated by its `boards.py`): the day ring and week strip on Today, the Progress
// charts, the estimate curve on the plan, and the two-ways trend on the on-track card.

// ── Rings ────────────────────────────────────────────────────────────────────────────────────

/** One decimal of precision is what the boards print (`:.1f` in the generator). */
const r1 = (n: number): number => Math.round(n * 10) / 10;
const s1 = (n: number): string => n.toFixed(1);
const clamp01 = (n: number) => Math.min(1, Math.max(0, n));

/**
 * The dash of a circular progress ring: the full circumference as the dasharray, and the offset
 * that leaves `share` of it drawn. Clamped at a full ring — a share past 1 draws the ring full and
 * never wraps, because an over-plan day is exactly the one that must be seen whole.
 *
 * r 44 is the phone's day ring (276.5 / 70.9 at 1,066 of 1,434), r 40 the web's, r 21 the macro
 * rings, r 12 the week strip's.
 */
export function ringDash(share: number, r: number): { dasharray: number; dashoffset: number } {
  const c = 2 * Math.PI * r;
  return { dasharray: r1(c), dashoffset: r1(c * (1 - clamp01(share))) };
}

/**
 * One day on the week strip, as the data knows it.
 *
 * `logged` is whether the diary holds anything for the day — it is NOT the same question as
 * `kcal > 0`, because "nothing recorded" draws differently on different days: today keeps its
 * instrument (the solid track, an accent ring at zero share), a past day gets the dotted
 * placeholder, and a future day is faded. `kcal` is the day's total and may be null while the
 * day itself is already known.
 */
export interface ChartDay {
  kcal: number | null;
  logged: boolean;
  when: "past" | "today" | "future";
}

/**
 * What a day is allowed to say on the week strip (and anywhere else a day's kcal meets its plan).
 *
 * There is no day-level "high", so amber never appears here: at or under the plan is `accent`,
 * past it is `bad`. The three empty states each have their own board: today with nothing yet is
 * `accent` at share zero — the solid track alone (`today-empty`); a past day with nothing logged
 * is `dotted`; a future day is `faded`, the dotted ring under a dimmed cell.
 */
export type DayTone = "accent" | "bad" | "dotted" | "faded";

export function dayTone(day: ChartDay, planKcal: number): DayTone {
  if (day.when === "future") return "faded";
  if (!day.logged) return day.when === "past" ? "dotted" : "accent";
  return (day.kcal ?? 0) > planKcal ? "bad" : "accent";
}

/** The week-strip ring's own frame, as every board draws it. */
export const WEEK_RING = {
  viewBox: "0 0 30 30",
  c: 15,
  r: 12,
  /** The placeholder circle's dash pattern, for `dotted` and `faded` days. */
  dottedDash: "2 3",
} as const;

/**
 * Tone and dash together for one week-strip ring — the strings a web renderer writes into
 * `stroke-dasharray`/`stroke-dashoffset`. A `dotted` or `faded` day draws the placeholder circle,
 * so it carries no offset.
 */
export function dayRing(
  day: ChartDay,
  planKcal: number,
): { tone: DayTone; dasharray: string; dashoffset?: string } {
  const tone = dayTone(day, planKcal);
  if (tone === "dotted" || tone === "faded") return { tone, dasharray: WEEK_RING.dottedDash };
  const d = ringDash((day.kcal ?? 0) / planKcal, WEEK_RING.r);
  return { tone, dasharray: s1(d.dasharray), dashoffset: s1(d.dashoffset) };
}

// ── The estimated-progress curve ─────────────────────────────────────────────────────────────
//
// The plan graph: the two ends and the month come from `projectGoal`, and everything between them
// is DRAWN, not read — the curve is Cal AI's eased shape, flat off the start weight and flat into
// the target, which is why it is labelled "Estimate" and no intermediate week is marked.

const pathNum = (n: number): string => `${r1(n)}`;

/**
 * The eased S from (x0, y0) to (x1, y1): horizontal tangents at both ends, handles a third of the
 * horizontal span in. For any frame that is not one of the fixed ones below — the fixed frames
 * carry the boards' own `d` strings verbatim.
 */
export function estimateCurvePath(x0: number, y0: number, x1: number, y1: number): string {
  const dx = x1 - x0;
  return `M${pathNum(x0)} ${pathNum(y0)} C${pathNum(x0 + dx / 3)} ${pathNum(y0)} ${pathNum(x1 - dx / 3)} ${pathNum(y1)} ${pathNum(x1)} ${pathNum(y1)}`;
}

/** The same curve closed to the baseline — the filled area under it. */
export function estimateAreaPath(
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  baselineY: number,
): string {
  return `${estimateCurvePath(x0, y0, x1, y1)} L${pathNum(x1)} ${pathNum(baselineY)} L${pathNum(x0)} ${pathNum(baselineY)} Z`;
}

/**
 * Which way the curve runs. `maintain` has no projection (`projectGoal` is null), so no chart —
 * the caller decides that before reaching for this.
 */
export type EstimateDirection = "lose" | "gain";

/**
 * The canonical estimate chart — the plan board's 320 × 168 frame, also on How it works' context,
 * the Progress goal card and the landing. Positions only: the labels ("Now", the month with
 * "· estimate", the start weight, the target chip) are the surface's words.
 *
 * The paths are the drawn ones, verbatim — the shape between the two ends is drawn, not read, so
 * the constants hold the board's own handles rather than a re-derived curve. A `gain` chart is the
 * lose drawing mirrored about the band's centre (y′ = 144 − y): the endpoints swap heights, the
 * target chip follows the end, and the baseline and captions do not move.
 */
export function estimateChart(direction: EstimateDirection): {
  viewBox: string;
  baseline: { x1: number; x2: number; y: number };
  linePath: string;
  areaPath: string;
  areaGradient: { stops: { offset: number; opacity: number }[] };
  startDot: { cx: number; cy: number; r: number };
  endDot: { cx: number; cy: number; r: number; strokeWidth: number };
  targetChip: { x: number; y: number; width: number; height: number; rx: number; textX: number; textY: number };
  startLabel: { x: number; y: number };
  nowLabel: { x: number; y: number };
  monthLabel: { x: number; y: number };
} {
  const lose = direction === "lose";
  const y0 = lose ? 34 : 110;
  const y1 = lose ? 110 : 34;
  return {
    viewBox: "0 0 320 168",
    baseline: { x1: 20, x2: 300, y: 138 },
    linePath: lose ? "M20 34 C110 34 200 110 292 110" : "M20 110 C110 110 200 34 292 34",
    areaPath: lose
      ? "M20 34 C110 34 200 110 292 110 L292 138 L20 138 Z"
      : "M20 110 C110 110 200 34 292 34 L292 138 L20 138 Z",
    /** The area's fade: accent at 24 % dissolving down, vertical. */
    areaGradient: { stops: [{ offset: 0, opacity: 0.24 }, { offset: 1, opacity: 0 }] },
    startDot: { cx: 20, cy: y0, r: 5 },
    endDot: { cx: 292, cy: y1, r: 6, strokeWidth: 2.5 },
    /** The "Target {n}" pill: its right edge sits 12 past the curve's end, its edge toward the end dot 28 off the dot's rim — clear of the curve, which the chip once crossed (#112). */
    targetChip: { x: 198, y: lose ? 48 : 68, width: 106, height: 28, rx: 8, textX: 251, textY: lose ? 67 : 87 },
    startLabel: { x: 20, y: lose ? 22 : 122 },
    nowLabel: { x: 20, y: 158 },
    monthLabel: { x: 300, y: 158 },
  };
}

/**
 * How it works step 3's mini curve — the same drawn shape in a 320 × 96 frame, verbatim from
 * `onboarding/02-how`. Drawn once, for the persona's lose direction; a client that needs it
 * mirrored reaches for `estimateCurvePath`.
 */
export const ESTIMATE_CHART_MINI = {
  viewBox: "0 0 320 96",
  linePath: "M16 18 C100 18 180 70 296 70",
  areaPath: "M16 18 C100 18 180 70 296 70 L296 88 L16 88 Z",
  areaGradient: { stops: [{ offset: 0, opacity: 0.24 }, { offset: 1, opacity: 0 }] },
  startDot: { cx: 16, cy: 18, r: 4.5 },
  endDot: { cx: 296, cy: 70, r: 5, strokeWidth: 2 },
  targetChip: { x: 212, y: 34, width: 92, height: 24, rx: 7, textX: 258, textY: 50 },
  startLabel: { x: 16, y: 10 },
} as const;

// ── The with-a-plan vs without chart ─────────────────────────────────────────────────────────
//
// Two fixed shapes and no numbers, no unit, no timescale — the chart states nothing a claims rule
// could refuse. Its accessible name is copy, not geometry — the settled wording is "Weight over
// time, drawn two ways: with a plan and without" (challenge #8), and it reaches this module's
// callers as a localized key, never a literal here.

export const TWO_WAYS_CHART = {
  viewBox: "0 0 320 170",
  baseline: { x1: 16, x2: 304, y: 140 },
  /** Without a plan: the faint upper line. */
  withoutPath: "M16 36 C70 44 92 96 150 94 S230 64 304 40",
  /** With a plan: the accent lower line. */
  withPath: "M16 36 C80 44 120 104 180 110 S260 114 304 114",
  startDot: { cx: 16, cy: 36, r: 5 },
  nowLabel: { x: 16, y: 162 },
  laterLabel: { x: 304, y: 162 },
  withoutLabel: { x: 304, y: 30 },
} as const;

// ── The logged-weight line chart ─────────────────────────────────────────────────────────────
//
// Progress's "Weight" card: points from data (a weigh-in is a dot, never interpolated), a polyline
// through them, three hairline rows, the first and last values written at their ends and the dates
// underneath. The 90D · 6M · 1Y · All segments pick which logged points reach this function; the
// axis itself always spans first-to-last point, which is what the board draws.

/** The range segments, in the board's order. `all` is the whole log. */
export const WEIGHT_RANGES = ["90D", "6M", "1Y", "all"] as const;
export type WeightRange = (typeof WEIGHT_RANGES)[number];

export interface WeightPoint {
  /** Where the weigh-in sits on the axis — epoch ms or a day index, one unit throughout. */
  t: number;
  kg: number;
}

const W_VIEW_BOX = "0 0 320 112";
const W_X0 = 20, W_X1 = 310;
const W_GRID = [22, 58, 94] as const;
/** Pixels per kg while the data allows it — the board's own 46. */
const W_PX_PER_KG = 46;
/** Headroom above the highest weigh-in, in kg. */
const W_TOP_PAD_KG = 0.2;

/**
 * Points → the polyline and its dots. y runs top-down: the top hairline (22) sits `W_TOP_PAD_KG`
 * above the highest weigh-in, at `W_PX_PER_KG` px per kg; when the span would overrun the bottom
 * hairline (94) the scale shrinks to fit — `min(46, 72 / (range + 0.2))`.
 */
/**
 * `withTargetLane` opens the You board's bottom lane: a dashed accent line in the band the taller
 * viewBox adds, its label above — DISPLAY, never the data scale (a 6 kg drop would sit off any
 * scale the three gridlines span). Off, the geometry is the board's plain one. The lane's VALUE
 * lives on its label, which the caller formats — the line means "the aim sits here".
 */
export function weightChart(points: readonly WeightPoint[], withTargetLane = false): {
  viewBox: string;
  gridlines: readonly number[];
  points: { x: number; y: number }[];
  path: string;
  firstLabel: { x: number; y: number };
  lastLabel: { x: number; y: number };
  /** The y of the two date captions; their x's are the axis ends. */
  dateLabelY: number;
  dateLabelX: { start: number; end: number };
  /** The dashed target line, when one was asked for — you.html's lane at the band's bottom. */
  targetLine?: { x1: number; x2: number; y: number };
  /** Where its "{w} · target" label sits, right-aligned just over the line. */
  targetLabel?: { x: number; y: number };
} {
  const kgs = points.map((p) => p.kg);
  const max = kgs.length ? Math.max(...kgs) : 0;
  const range = kgs.length ? max - Math.min(...kgs) : 0;
  const pxPerKg = Math.min(W_PX_PER_KG, (W_GRID[2] - W_GRID[0]) / (range + W_TOP_PAD_KG));
  const refKg = max + W_TOP_PAD_KG;
  const t0 = points[0]?.t ?? 0;
  const tN = points[points.length - 1]?.t ?? 0;
  const span = tN - t0;

  const pts = points.map((p) => ({
    x: Math.round(W_X0 + (span > 0 ? ((p.t - t0) / span) * (W_X1 - W_X0) : 0)),
    y: Math.round(W_GRID[0] + (refKg - p.kg) * pxPerKg),
  }));

  const last = pts[pts.length - 1];
  return {
    viewBox: withTargetLane ? "0 0 320 120" : W_VIEW_BOX,
    gridlines: W_GRID,
    points: pts,
    // A line needs two points: one weigh-in is a dot with its date, not a trend (design-pro, #95).
    path: pts.length > 1 ? `M${pts.map((p) => `${p.x} ${p.y}`).join(" L")}` : "",
    firstLabel: { x: W_X0, y: 14 },
    // With the lane open the label keeps clear of it: its anchor tops out above the target
    // line (y 104) rather than writing over it when the newest point sits at the bottom of range.
    lastLabel: last
      ? { x: last.x - 10, y: withTargetLane ? Math.min(last.y + 4, 88) : last.y + 4 }
      : { x: W_X1, y: 90 },
    dateLabelY: withTargetLane ? 118 : 110,
    dateLabelX: { start: W_X0, end: W_X1 },
    ...(withTargetLane ? {
      // The band the taller frame opens: the board's lane at y 104, its label above it, both the
      // chart's inner width (24 → 296). The value lives on the label, not the axis — the line
      // says "the aim sits here", never a scale reading.
      targetLine: { x1: 24, x2: 296, y: 104 },
      targetLabel: { x: 296, y: 98 },
    } : {}),
  };
}

// ── The week's intake bars ────────────────────────────────────────────────────────────────────
//
// Progress's "This week" card: one bar a day against a dashed plan line, today picked out with a
// tint fill and an outline. The scale is the board's own — 1900 kcal of headroom over the baseline
// — and it yields to the data: past ~1.1× the largest figure on the card (plan or day), the px per
// kcal shrink so a 2,800-kcal plan and a 3,200-kcal day still fit the 142-tall viewBox. A bar over
// plan simply clears the dashed line and keeps going.

const BARS_BASE = 118;
/** The board's headroom: 100 px of bar for every 1,900 kcal. */
const BARS_BASELINE_FULL = 1900;

export function weekBars(
  days: readonly (number | null)[],
  planKcal: number,
  todayIndex = -1,
): {
  viewBox: string;
  planLine: { x1: number; x2: number; y: number };
  planLabel: { x: number; y: number };
  bars: ({ x: number; y: number; width: number; height: number; rx: number; tone: DayTone; today: boolean } | null)[];
  /** The day-letter captions, one per day whether it has a bar or not. */
  labels: { x: number; y: number }[];
} {
  const largest = Math.max(planKcal, ...days.map((d) => d ?? 0));
  const pxPerKcal = 100 / Math.max(BARS_BASELINE_FULL, largest * 1.1);
  const planY = Math.round(BARS_BASE - planKcal * pxPerKcal);
  return {
    viewBox: "0 0 320 142",
    planLine: { x1: 8, x2: 312, y: planY },
    planLabel: { x: 312, y: planY - 6 },
    bars: days.map((kcal, i) => {
      if (kcal === null) return null;
      const h = Math.round(kcal * pxPerKcal);
      return {
        x: 14 + i * 44,
        y: BARS_BASE - h,
        width: 26,
        height: h,
        rx: 4,
        tone: dayTone({ kcal, logged: true, when: i === todayIndex ? "today" : "past" }, planKcal),
        today: i === todayIndex,
      };
    }),
    labels: days.map((_, i) => ({ x: 14 + i * 44 + 13, y: 136 })),
  };
}

// ── The goal progress bar ────────────────────────────────────────────────────────────────────
//
// Progress's goal card: `start → target` with the fill at the share already covered, "0.6 kg down"
// and "5.4 to go" beneath. Works in both directions — a gain goal's done/to-go run the other way.

export function goalBar(
  startKg: number,
  currentKg: number,
  targetKg: number,
): { share: number; doneKg: number; toGoKg: number } {
  const span = targetKg - startKg;
  if (span === 0) return { share: 1, doneKg: 0, toGoKg: 0 };
  const dir = Math.sign(span);
  const done = (currentKg - startKg) * dir;
  const toGo = (targetKg - currentKg) * dir;
  return {
    share: Math.round(clamp01(done / Math.abs(span)) * 1e4) / 1e4,
    doneKg: r1(Math.max(0, done)),
    toGoKg: r1(Math.max(0, toGo)),
  };
}

// ── The BMI bar ──────────────────────────────────────────────────────────────────────────────
//
// The last card on Progress: four neutral segments and a tick where the value lands
// (`product/design/pro/boards.py` `BMI_RANGES` / `_BPOS`). The SEGMENT bounds are the ones the
// labels print — "18.5–24.9" — while `scores.ts`'s `BMI_BANDS` derives its membership edges from
// this table, so a moved edge cannot strand a label.

/**
 * The four segments, in bar order: the id `bmiRange` returns, and the printed bounds the label
 * under it is built from. `lo`/`hi` are null on the open ends — "below 18.5" has no floor and
 * "30 and above" no ceiling; the tick borrows the inner neighbour's width there.
 */
export const BMI_SEGMENTS = [
  { id: "below-18.5", lo: null, hi: 18.5 },
  { id: "18.5-24.9", lo: 18.5, hi: 24.9 },
  { id: "25-29.9", lo: 25, hi: 29.9 },
  { id: "30-plus", lo: 30, hi: null },
] as const;

/**
 * Where the value's tick sits across the whole bar, 0..1 — `boards.py`'s `_BPOS`: the segment
 * index plus the value's fraction through its bounds, over four. An open segment borrows the
 * inner neighbour's width, so a 17 or a 34 pins inside its own segment rather than at its edge —
 * and clamped, so no value ever draws the tick outside the bar.
 */
export function bmiTick(value: number, range: string): number {
  const i = BMI_SEGMENTS.findIndex((s) => s.id === range);
  if (i < 0) return 0;
  const seg = BMI_SEGMENTS[i]!;
  const wLow = BMI_SEGMENTS[1]!.hi! - BMI_SEGMENTS[1]!.lo!;
  const wHigh = BMI_SEGMENTS[2]!.hi! - BMI_SEGMENTS[2]!.lo!;
  const lo = seg.lo ?? seg.hi! - wLow;
  const hi = seg.hi ?? seg.lo! + wHigh;
  return (i + clamp01((value - lo) / (hi - lo))) / BMI_SEGMENTS.length;
}
