// Chart geometry — the numbers every Register P chart is drawn with, computed once.
//
// This module is geometry ONLY: path `d` strings, dash values, viewBoxes and the positions of the
// labels a surface then fills in its own language. No colour, no copy — a tone is a name a client
// maps onto the S1 tokens, and a string position is where a translated label sits.
//
// Every pinned number below is what the boards draw (`product/design/pro` on ieat-app main
// d3fe6ef8, generated by its `boards.py`): the day ring and week strip on Today, the Progress
// charts, the estimate curve on the plan, and the two-ways trend on the on-track card.

// ── Rings ────────────────────────────────────────────────────────────────────────────────────

/** One decimal of precision is what the boards print (`:.1f` in the generator). */
const r1 = (n: number): number => Math.round(n * 10) / 10;
const s1 = (n: number): string => n.toFixed(1);
const clamp01 = (n: number) => Math.min(1, Math.max(0, n));

/**
 * The dash of a circular progress ring: the full circumference as the dasharray, and the offset
 * that leaves `share` of it drawn. Clamped at a full ring — a share past 1 draws the ring full and
 * never wraps, because an over-plan day is exactly the one that must be seen whole.
 *
 * r 44 is the phone's day ring (276.5 / 70.9 at 1,066 of 1,434), r 40 the web's, r 21 the macro
 * rings, r 12 the week strip's.
 */
export function ringDash(share: number, r: number): { dasharray: number; dashoffset: number } {
  const c = 2 * Math.PI * r;
  return { dasharray: r1(c), dashoffset: r1(c * (1 - clamp01(share))) };
}

/**
 * What a day is allowed to say on the week strip (and anywhere else a day's kcal meets its plan).
 *
 * There is no day-level "high", so amber never appears here: at or under the plan is `accent`,
 * past it is `bad`. `null` kcal — no reading at all — is `dotted`, the placeholder circle. A
 * future day is `faded`: the same dotted ring under a dimmed cell, which is why `future` is a
 * flag and not something the kcal can say. A logged day that recorded nothing is 0, not null —
 * an accent ring at zero share, i.e. just its track.
 */
export type DayTone = "accent" | "bad" | "dotted" | "faded";

export function dayTone(kcal: number | null, planKcal: number, future = false): DayTone {
  if (future) return "faded";
  if (kcal === null) return "dotted";
  return kcal > planKcal ? "bad" : "accent";
}

/** The week-strip ring's own frame, as every board draws it. */
export const WEEK_RING = {
  viewBox: "0 0 30 30",
  c: 15,
  r: 12,
  /** The placeholder circle's dash pattern, for `dotted` and `faded` days. */
  dottedDash: "2 3",
} as const;

/**
 * Tone and dash together for one week-strip ring — the strings a web renderer writes into
 * `stroke-dasharray`/`stroke-dashoffset`. A `dotted` or `faded` day draws the placeholder circle,
 * so it carries no offset.
 */
export function dayRing(
  kcal: number | null,
  planKcal: number,
  future = false,
): { tone: DayTone; dasharray: string; dashoffset?: string } {
  const tone = dayTone(kcal, planKcal, future);
  if (tone === "dotted" || tone === "faded") return { tone, dasharray: WEEK_RING.dottedDash };
  const d = ringDash((kcal ?? 0) / planKcal, WEEK_RING.r);
  return { tone, dasharray: s1(d.dasharray), dashoffset: s1(d.dashoffset) };
}

// ── The estimated-progress curve ─────────────────────────────────────────────────────────────
//
// The plan graph: the two ends and the month come from `projectGoal`, and everything between them
// is DRAWN, not read — the curve is Cal AI's eased shape, flat off the start weight and flat into
// the target, which is why it is labelled "Estimate" and no intermediate week is marked.

const pathNum = (n: number): string => `${r1(n)}`;

/**
 * The eased S from (x0, y0) to (x1, y1): horizontal tangents at both ends, handles a third of the
 * horizontal span in. The boards' hand-drawn handles sit within a pixel of this on every surface.
 */
export function estimateCurvePath(x0: number, y0: number, x1: number, y1: number): string {
  const dx = x1 - x0;
  return `M${pathNum(x0)} ${pathNum(y0)} C${pathNum(x0 + dx / 3)} ${pathNum(y0)} ${pathNum(x1 - dx / 3)} ${pathNum(y1)} ${pathNum(x1)} ${pathNum(y1)}`;
}

/** The same curve closed to the baseline — the filled area under it. */
export function estimateAreaPath(
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  baselineY: number,
): string {
  return `${estimateCurvePath(x0, y0, x1, y1)} L${pathNum(x1)} ${pathNum(baselineY)} L${pathNum(x0)} ${pathNum(baselineY)} Z`;
}

/**
 * The canonical estimate chart — the plan board's 320 × 168 frame. Positions only: the labels
 * ("Now", the month with "· estimate", the start weight, the target chip) are the surface's words.
 *
 * `curve`/`area` are computed through `estimateCurvePath`/`estimateAreaPath`, so the mini curve in
 * How it works step 3 (320 × 96) is the same helper with its own endpoints, not a second drawing.
 */
export const ESTIMATE_CHART = (() => {
  const x0 = 20, y0 = 34, x1 = 292, y1 = 110, baseY = 138;
  return {
    viewBox: "0 0 320 168",
    baseline: { x1: 20, x2: 300, y: baseY },
    linePath: estimateCurvePath(x0, y0, x1, y1),
    areaPath: estimateAreaPath(x0, y0, x1, y1, baseY),
    /** The area's fade: accent at 24 % dissolving down, vertical. */
    areaGradient: { stops: [{ offset: 0, opacity: 0.24 }, { offset: 1, opacity: 0 }] },
    startDot: { cx: x0, cy: y0, r: 5 },
    endDot: { cx: x1, cy: y1, r: 6, strokeWidth: 2.5 },
    /** The "Target {n}" pill: its right edge sits 12 past the curve's end, its centre 28 above it. */
    targetChip: { x: 198, y: 68, width: 106, height: 28, rx: 8, textX: 251, textY: 87 },
    startLabel: { x: x0, y: 22 },
    nowLabel: { x: x0, y: 158 },
    monthLabel: { x: 300, y: 158 },
  } as const;
})();

// ── The with-a-plan vs without chart ─────────────────────────────────────────────────────────
//
// Two fixed shapes and no numbers, no unit, no timescale — the chart states nothing a claims rule
// could refuse. The accessible name is the wording challenge #8 settled, exactly: a name that
// describes the drawing without speaking the promise the drawing only suggests.

export const TWO_WAYS_CHART = {
  viewBox: "0 0 320 170",
  /** The exact accessible name — do not reword. */
  a11yName: "Weight over time, drawn two ways: with a plan and without",
  baseline: { x1: 16, x2: 304, y: 140 },
  /** Without a plan: the faint upper line. */
  withoutPath: "M16 36 C70 44 92 96 150 94 S230 64 304 40",
  /** With a plan: the accent lower line. */
  withPath: "M16 36 C80 44 120 104 180 110 S260 114 304 114",
  startDot: { cx: 16, cy: 36, r: 5 },
  nowLabel: { x: 16, y: 162 },
  laterLabel: { x: 304, y: 162 },
  withoutLabel: { x: 304, y: 30 },
} as const;

// ── The logged-weight line chart ─────────────────────────────────────────────────────────────
//
// Progress's "Weight" card: points from data (a weigh-in is a dot, never interpolated), a polyline
// through them, three hairline rows, the first and last values written at their ends and the dates
// underneath. The 90D · 6M · 1Y · All segments pick which logged points reach this function; the
// axis itself always spans first-to-last point, which is what the board draws.

/** The range segments, in the board's order. `all` is the whole log. */
export const WEIGHT_RANGES = ["90D", "6M", "1Y", "all"] as const;
export type WeightRange = (typeof WEIGHT_RANGES)[number];

export interface WeightPoint {
  /** Where the weigh-in sits on the axis — epoch ms or a day index, one unit throughout. */
  t: number;
  kg: number;
}

const W_VIEW_BOX = "0 0 320 112";
const W_X0 = 20, W_X1 = 310;
const W_GRID = [22, 58, 94] as const;
/** Pixels per kg while the data allows it — the board's own 46. */
const W_PX_PER_KG = 46;
/** Headroom above the highest weigh-in, in kg. */
const W_TOP_PAD_KG = 0.2;

/**
 * Points → the polyline and its dots. y runs top-down: the top hairline (22) sits `W_TOP_PAD_KG`
 * above the highest weigh-in, at `W_PX_PER_KG` px per kg; when the span would overrun the bottom
 * hairline (94) the scale shrinks to fit — `min(46, 72 / (range + 0.2))`.
 */
export function weightChart(points: readonly WeightPoint[]): {
  viewBox: string;
  gridlines: readonly number[];
  points: { x: number; y: number }[];
  path: string;
  firstLabel: { x: number; y: number };
  lastLabel: { x: number; y: number };
  /** The y of the two date captions; their x's are the axis ends. */
  dateLabelY: number;
  dateLabelX: { start: number; end: number };
} {
  const kgs = points.map((p) => p.kg);
  const max = kgs.length ? Math.max(...kgs) : 0;
  const range = kgs.length ? max - Math.min(...kgs) : 0;
  const pxPerKg = Math.min(W_PX_PER_KG, (W_GRID[2] - W_GRID[0]) / (range + W_TOP_PAD_KG));
  const refKg = max + W_TOP_PAD_KG;
  const t0 = points[0]?.t ?? 0;
  const tN = points[points.length - 1]?.t ?? 0;
  const span = tN - t0;

  const pts = points.map((p) => ({
    x: Math.round(W_X0 + (span > 0 ? ((p.t - t0) / span) * (W_X1 - W_X0) : 0)),
    y: Math.round(W_GRID[0] + (refKg - p.kg) * pxPerKg),
  }));

  const last = pts[pts.length - 1];
  return {
    viewBox: W_VIEW_BOX,
    gridlines: W_GRID,
    points: pts,
    path: pts.length ? `M${pts.map((p) => `${p.x} ${p.y}`).join(" L")}` : "",
    firstLabel: { x: W_X0, y: 14 },
    lastLabel: last ? { x: last.x - 10, y: last.y + 4 } : { x: W_X1, y: 90 },
    dateLabelY: 110,
    dateLabelX: { start: W_X0, end: W_X1 },
  };
}

// ── The week's intake bars ────────────────────────────────────────────────────────────────────
//
// Progress's "This week" card: one bar a day against a dashed plan line, today picked out with a
// tint fill and an outline. The scale is the board's own — 1900 kcal of headroom over the baseline
// — so a bar over plan simply clears the dashed line and keeps going.

const BARS_BASE = 118;
const BARS_PX_PER_KCAL = 100 / 1900;

export function weekBars(
  days: readonly (number | null)[],
  planKcal: number,
  todayIndex = -1,
): {
  viewBox: string;
  planLine: { x1: number; x2: number; y: number };
  planLabel: { x: number; y: number };
  bars: ({ x: number; y: number; width: number; height: number; rx: number; tone: DayTone; today: boolean } | null)[];
  /** The day-letter captions, one per day whether it has a bar or not. */
  labels: { x: number; y: number }[];
} {
  const planY = Math.round(BARS_BASE - planKcal * BARS_PX_PER_KCAL);
  return {
    viewBox: "0 0 320 142",
    planLine: { x1: 8, x2: 312, y: planY },
    planLabel: { x: 312, y: planY - 6 },
    bars: days.map((kcal, i) => {
      if (kcal === null) return null;
      const h = Math.round(kcal * BARS_PX_PER_KCAL);
      return {
        x: 14 + i * 44,
        y: BARS_BASE - h,
        width: 26,
        height: h,
        rx: 4,
        tone: dayTone(kcal, planKcal),
        today: i === todayIndex,
      };
    }),
    labels: days.map((_, i) => ({ x: 14 + i * 44 + 13, y: 136 })),
  };
}

// ── The goal progress bar ────────────────────────────────────────────────────────────────────
//
// Progress's goal card: `start → target` with the fill at the share already covered, "0.6 kg down"
// and "5.4 to go" beneath. Works in both directions — a gain goal's done/to-go run the other way.

export function goalBar(
  startKg: number,
  currentKg: number,
  targetKg: number,
): { share: number; doneKg: number; toGoKg: number } {
  const span = targetKg - startKg;
  if (span === 0) return { share: 1, doneKg: 0, toGoKg: 0 };
  const dir = Math.sign(span);
  const done = (currentKg - startKg) * dir;
  const toGo = (targetKg - currentKg) * dir;
  return {
    share: Math.round(clamp01(done / Math.abs(span)) * 1e4) / 1e4,
    doneKg: r1(Math.max(0, done)),
    toGoKg: r1(Math.max(0, toGo)),
  };
}
