// Chart geometry — the numbers every Register P chart is drawn with, computed once.
//
// This module is geometry ONLY: path `d` strings, dash values, viewBoxes and the positions of the
// labels a surface then fills in its own language. No colour, no copy — a tone is a name a client
// maps onto the S1 tokens, and a string position is where a translated label sits.
//
// Every pinned number below is what the boards draw (`product/design/pro` on ieat-app main
// d3fe6ef8, generated by its `boards.py`): the day ring and week strip on Today, the Progress
// charts, the estimate curve on the plan, and the two-ways trend on the on-track card.

// ── Rings ────────────────────────────────────────────────────────────────────────────────────

/** One decimal of precision is what the boards print (`:.1f` in the generator). */
const r1 = (n: number): number => Math.round(n * 10) / 10;
const s1 = (n: number): string => n.toFixed(1);
const clamp01 = (n: number) => Math.min(1, Math.max(0, n));

/**
 * The dash of a circular progress ring: the full circumference as the dasharray, and the offset
 * that leaves `share` of it drawn. Clamped at a full ring — a share past 1 draws the ring full and
 * never wraps, because an over-plan day is exactly the one that must be seen whole.
 *
 * r 44 is the phone's day ring (276.5 / 70.9 at 1,066 of 1,434), r 40 the web's, r 21 the macro
 * rings, r 12 the week strip's.
 */
export function ringDash(share: number, r: number): { dasharray: number; dashoffset: number } {
  const c = 2 * Math.PI * r;
  return { dasharray: r1(c), dashoffset: r1(c * (1 - clamp01(share))) };
}

/**
 * One day on the week strip, as the data knows it.
 *
 * `logged` is whether the diary holds anything for the day — it is NOT the same question as
 * `kcal > 0`, because "nothing recorded" draws differently on different days: today keeps its
 * instrument (the solid track, an accent ring at zero share), a past day gets the dotted
 * placeholder, and a future day is faded. `kcal` is the day's total and may be null while the
 * day itself is already known.
 */
export interface ChartDay {
  kcal: number | null;
  logged: boolean;
  when: "past" | "today" | "future";
}

/**
 * What a day is allowed to say on the week strip (and anywhere else a day's kcal meets its plan).
 *
 * There is no day-level "high", so amber never appears here: at or under the plan is `accent`,
 * past it is `bad`. The three empty states each have their own board: today with nothing yet is
 * `accent` at share zero — the solid track alone (`today-empty`); a past day with nothing logged
 * is `dotted`; a future day is `faded`, the dotted ring under a dimmed cell.
 */
export type DayTone = "accent" | "bad" | "dotted" | "faded";

export function dayTone(day: ChartDay, planKcal: number): DayTone {
  if (day.when === "future") return "faded";
  if (!day.logged) return day.when === "past" ? "dotted" : "accent";
  return (day.kcal ?? 0) > planKcal ? "bad" : "accent";
}

/** The week-strip ring's own frame, as every board draws it. */
export const WEEK_RING = {
  viewBox: "0 0 30 30",
  c: 15,
  r: 12,
  /** The placeholder circle's dash pattern, for `dotted` and `faded` days. */
  dottedDash: "2 3",
} as const;

/**
 * Tone and dash together for one week-strip ring — the strings a web renderer writes into
 * `stroke-dasharray`/`stroke-dashoffset`. A `dotted` or `faded` day draws the placeholder circle,
 * so it carries no offset.
 */
export function dayRing(
  day: ChartDay,
  planKcal: number,
): { tone: DayTone; dasharray: string; dashoffset?: string } {
  const tone = dayTone(day, planKcal);
  if (tone === "dotted" || tone === "faded") return { tone, dasharray: WEEK_RING.dottedDash };
  const d = ringDash((day.kcal ?? 0) / planKcal, WEEK_RING.r);
  return { tone, dasharray: s1(d.dasharray), dashoffset: s1(d.dashoffset) };
}

// ── The estimated-progress curve ─────────────────────────────────────────────────────────────
//
// The plan graph: the two ends and the month come from `projectGoal`, and everything between them
// is DRAWN, not read — the curve is Cal AI's eased shape, flat off the start weight and flat into
// the target, which is why it is labelled "Estimate" and no intermediate week is marked.

const pathNum = (n: number): string => `${r1(n)}`;

/**
 * The eased S from (x0, y0) to (x1, y1): horizontal tangents at both ends, handles a third of the
 * horizontal span in. For any frame that is not one of the fixed ones below — the fixed frames
 * carry the boards' own `d` strings verbatim.
 */
export function estimateCurvePath(x0: number, y0: number, x1: number, y1: number): string {
  const dx = x1 - x0;
  return `M${pathNum(x0)} ${pathNum(y0)} C${pathNum(x0 + dx / 3)} ${pathNum(y0)} ${pathNum(x1 - dx / 3)} ${pathNum(y1)} ${pathNum(x1)} ${pathNum(y1)}`;
}

/** The same curve closed to the baseline — the filled area under it. */
export function estimateAreaPath(
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  baselineY: number,
): string {
  return `${estimateCurvePath(x0, y0, x1, y1)} L${pathNum(x1)} ${pathNum(baselineY)} L${pathNum(x0)} ${pathNum(baselineY)} Z`;
}

/**
 * Which way the curve runs. `maintain` has no projection (`projectGoal` is null), so no chart —
 * the caller decides that before reaching for this.
 */
export type EstimateDirection = "lose" | "gain";

/**
 * The canonical estimate chart — the plan board's 320 × 168 frame, also on How it works' context,
 * the Progress goal card and the landing. Positions only: the labels ("Now", the month with
 * "· estimate", the start weight, the target chip) are the surface's words.
 *
 * The paths are the drawn ones, verbatim — the shape between the two ends is drawn, not read, so
 * the constants hold the board's own handles rather than a re-derived curve. A `gain` chart is the
 * lose drawing mirrored about the band's centre (y′ = 144 − y): the endpoints swap heights, the
 * target chip follows the end, and the baseline and captions do not move.
 */
export function estimateChart(direction: EstimateDirection): {
  viewBox: string;
  baseline: { x1: number; x2: number; y: number };
  linePath: string;
  areaPath: string;
  areaGradient: { stops: { offset: number; opacity: number }[] };
  startDot: { cx: number; cy: number; r: number };
  endDot: { cx: number; cy: number; r: number; strokeWidth: number };
  targetChip: { x: number; y: number; width: number; height: number; rx: number; textX: number; textY: number };
  startLabel: { x: number; y: number };
  nowLabel: { x: number; y: number };
  monthLabel: { x: number; y: number };
} {
  const lose = direction === "lose";
  const y0 = lose ? 34 : 110;
  const y1 = lose ? 110 : 34;
  return {
    viewBox: "0 0 320 168",
    baseline: { x1: 20, x2: 300, y: 138 },
    linePath: lose ? "M20 34 C110 34 200 110 292 110" : "M20 110 C110 110 200 34 292 34",
    areaPath: lose
      ? "M20 34 C110 34 200 110 292 110 L292 138 L20 138 Z"
      : "M20 110 C110 110 200 34 292 34 L292 138 L20 138 Z",
    /** The area's fade: accent at 24 % dissolving down, vertical. */
    areaGradient: { stops: [{ offset: 0, opacity: 0.24 }, { offset: 1, opacity: 0 }] },
    startDot: { cx: 20, cy: y0, r: 5 },
    endDot: { cx: 292, cy: y1, r: 6, strokeWidth: 2.5 },
    /** The "Target {n}" pill: its right edge sits 12 past the curve's end, its edge toward the end dot 28 off the dot's rim — clear of the curve, which the chip once crossed (#112). */
    targetChip: { x: 198, y: lose ? 48 : 68, width: 106, height: 28, rx: 8, textX: 251, textY: lose ? 67 : 87 },
    startLabel: { x: 20, y: lose ? 22 : 122 },
    nowLabel: { x: 20, y: 158 },
    monthLabel: { x: 300, y: 158 },
  };
}

/**
 * How it works step 3's mini curve — the same drawn shape in a 320 × 96 frame, verbatim from
 * `onboarding/02-how`. Drawn once, for the persona's lose direction; a client that needs it
 * mirrored reaches for `estimateCurvePath`.
 */
export const ESTIMATE_CHART_MINI = {
  viewBox: "0 0 320 96",
  linePath: "M16 18 C100 18 180 70 296 70",
  areaPath: "M16 18 C100 18 180 70 296 70 L296 88 L16 88 Z",
  areaGradient: { stops: [{ offset: 0, opacity: 0.24 }, { offset: 1, opacity: 0 }] },
  startDot: { cx: 16, cy: 18, r: 4.5 },
  endDot: { cx: 296, cy: 70, r: 5, strokeWidth: 2 },
  targetChip: { x: 212, y: 34, width: 92, height: 24, rx: 7, textX: 258, textY: 50 },
  startLabel: { x: 16, y: 10 },
} as const;

// ── The with-a-plan vs without chart ─────────────────────────────────────────────────────────
//
// Two fixed shapes and no numbers, no unit, no timescale — the chart states nothing a claims rule
// could refuse. Its accessible name is copy, not geometry — the settled wording is "Weight over
// time, drawn two ways: with a plan and without" (challenge #8), and it reaches this module's
// callers as a localized key, never a literal here.

export const TWO_WAYS_CHART = {
  viewBox: "0 0 320 170",
  baseline: { x1: 16, x2: 304, y: 140 },
  /** Without a plan: the faint upper line. */
  withoutPath: "M16 36 C70 44 92 96 150 94 S230 64 304 40",
  /** With a plan: the accent lower line. */
  withPath: "M16 36 C80 44 120 104 180 110 S260 114 304 114",
  startDot: { cx: 16, cy: 36, r: 5 },
  nowLabel: { x: 16, y: 162 },
  laterLabel: { x: 304, y: 162 },
  withoutLabel: { x: 304, y: 30 },
} as const;

// ── The logged-weight line chart ─────────────────────────────────────────────────────────────
//
// Progress's "Weight" card: the line draws the TREND of the weigh-ins — a 7-day rolling mean,
// never the raw samples, which a daily log polylines into scribbles a few px apart (#1114) —
// with three hairline rows, the first and last values written at their ends and the dates
// underneath. The 90D · 6M · 1Y · All segments pick which logged points reach this function; the
// axis itself always spans first-to-last point, which is what the board draws.

/** The range segments, in the board's order. `all` is the whole log. */
export const WEIGHT_RANGES = ["90D", "6M", "1Y", "all"] as const;
export type WeightRange = (typeof WEIGHT_RANGES)[number];

export interface WeightPoint {
  /** Where the weigh-in sits on the axis — epoch ms or a day index, one unit throughout. */
  t: number;
  kg: number;
}

const W_VIEW_BOX = "0 0 320 112";
const W_X0 = 20, W_X1 = 310;
const W_GRID = [22, 58, 94] as const;
/** Pixels per kg while the data allows it — the board's own 46. */
const W_PX_PER_KG = 46;
/** Headroom above the highest weigh-in, in kg. */
const W_TOP_PAD_KG = 0.2;

/**
 * One weigh-in line, two frames — `weightChart` (the Progress card, 320×112, hairlines) and
 * `bodyWeightChart` (the Body screen, 340×130, bare). The MAPPING is one function so the scale's
 * rule — px/kg capped, shrinking when the span would overrun the frame — cannot drift between the
 * card that announces the trend and the screen that shows it. What differs lives in the frame:
 * the viewBox, the axis ends, the scale's own numbers, and where the four captions anchor.
 */
interface WeightFrame {
  viewBox: string;
  /** The x of the first slot and the axis' right end — the date captions read off them. */
  x0: number;
  x1: number;
  /** The y the weight axis tops at — the top hairline's y, or the bare frame's top. */
  yTop: number;
  /** kg of headroom above the max, in BOTH the scale's reference and the range it divides. */
  topPadKg: number;
  /** px per kg while the data allows it. */
  pxPerKg: number;
  /** The pixel span the drawn range must fit inside. */
  spanPx: number;
  /** The smallest range the scale divides by — a flat log still needs a scale. */
  minRange: number;
  firstLabelY: number;
  /** The last label sits this far under the end dot. */
  lastLabelDy: number;
  /** The empty log's label y, at the axis' end. */
  emptyLabelY: number;
  dateLabelY: number;
  /** The hairlines the frame draws — the Body board draws none. */
  gridlines?: readonly number[];
}

const W_FRAME: WeightFrame = {
  viewBox: W_VIEW_BOX,
  x0: W_X0, x1: W_X1,
  yTop: W_GRID[0]!,
  topPadKg: W_TOP_PAD_KG,
  pxPerKg: W_PX_PER_KG,
  // The scale the board owns: the two-kg span between the top and bottom hairlines.
  spanPx: W_GRID[2]! - W_GRID[0]!,
  minRange: 0,
  firstLabelY: 14,
  lastLabelDy: 4,
  emptyLabelY: 90,
  dateLabelY: 110,
  gridlines: W_GRID,
};

/**
 * The same frame with the You board's bottom lane open — taller, and its drawn range compressed
 * to the top band (the board's line spans y 30–54, nowhere near the lane at 104): the end label
 * drops the board's 18 under its point and never meets the lane's own label (#303).
 */
const W_FRAME_LANE: WeightFrame = {
  ...W_FRAME, viewBox: "0 0 320 120", spanPx: 32, lastLabelDy: 18, dateLabelY: 118,
};

/** health-body.html's frame: wider, no hairlines, the board's 50 px a kg capping at a 66 px span. */
const BW_FRAME: WeightFrame = {
  viewBox: "0 0 340 130",
  x0: 20, x1: 320,
  yTop: 30,
  topPadKg: 0,
  pxPerKg: 50,
  spanPx: 66,
  minRange: 0.5,
  firstLabelY: 18,
  lastLabelDy: 12,
  emptyLabelY: 100,
  dateLabelY: 128,
};

/** The trend's window: the trailing 7 days a daily scale's ±0.3 kg swing is averaged over. */
const W_TREND_WINDOW_DAYS = 7;
/** Past this drawn-point count the polyline is ink, not shape — under ~7 px a point on the axis. */
const W_TREND_MAX_POINTS = 40;
/** A span this short or shorter thins to a weekly sample of the trend; longer goes monthly. */
const W_TREND_WEEKLY_SPAN_DAYS = 120;

/**
 * The trend a weigh-in line draws (#1114): each point re-valued as the mean of the readings in
 * the 7 days up to it, so the line follows where the weight is going rather than every day's
 * noise. `t` is epoch ms or a day index — the constants are days, scaled by whichever the caller
 * sent (a day index is never a billion; an epoch-ms reading always is). Sparse logs come through
 * untouched — a window holding one reading returns it — and the endpoints keep their dates, so
 * the line still runs first weigh-in to last. The labels at the ends name what the line ends ON
 * (`firstValue`/`lastValue`), never the raw readings; the card's big figure stays the latest
 * weigh-in, which the callers hold separately.
 *
 * A rolling mean smooths without thinning: a daily log stays one point a day, and past
 * `W_TREND_MAX_POINTS` the frame cannot carry them — so a crowded series is sampled back to a
 * weekly step on a ~4-month span or shorter (the 90D segment) and a monthly one past it (6M, 1Y,
 * the whole log), each kept point still the trailing mean at its own date, the ends pinned.
 */
function weightTrend(points: readonly WeightPoint[]): WeightPoint[] {
  if (points.length < 3) return [...points];
  const day = points[points.length - 1]!.t >= 1_000_000_000 ? 86_400_000 : 1;
  const window = W_TREND_WINDOW_DAYS * day;
  const mean = points.map((p, i) => {
    let sum = 0, n = 0;
    for (let j = i; j >= 0 && p.t - points[j]!.t <= window; j--) {
      sum += points[j]!.kg;
      n++;
    }
    return { t: p.t, kg: sum / n };
  });
  if (mean.length <= W_TREND_MAX_POINTS) return mean;
  const step = ((mean[mean.length - 1]!.t - mean[0]!.t) / day <= W_TREND_WEEKLY_SPAN_DAYS
    ? 7 : 30) * day;
  const out = [mean[0]!];
  for (const p of mean.slice(1, -1)) {
    if (p.t - out[out.length - 1]!.t >= step) out.push(p);
  }
  out.push(mean[mean.length - 1]!);
  return out;
}

function weightLine(points: readonly WeightPoint[], f: WeightFrame): {
  viewBox: string;
  gridlines: readonly number[];
  points: { x: number; y: number }[];
  path: string;
  /**
   * The drawn endpoints' values, in the caller's own unit — what the end labels must name
   * (#1114): the TREND's first and last points, so a label anchored to the line's end can never
   * quote a reading the line no longer ends at. Null on an empty log.
   */
  firstValue: number | null;
  lastValue: number | null;
  firstLabel: { x: number; y: number };
  lastLabel: { x: number; y: number };
  dateLabelY: number;
  dateLabelX: { start: number; end: number };
} {
  const kgs = points.map((p) => p.kg);
  const max = kgs.length ? Math.max(...kgs) : 0;
  const range = kgs.length ? max - Math.min(...kgs) : 0;
  const pxPerKg = Math.min(f.pxPerKg, f.spanPx / Math.max(range + f.topPadKg, f.minRange));
  const refKg = max + f.topPadKg;
  const t0 = points[0]?.t ?? 0;
  const span = (points[points.length - 1]?.t ?? 0) - t0;

  const pts = points.map((p) => ({
    x: Math.round(f.x0 + (span > 0 ? ((p.t - t0) / span) * (f.x1 - f.x0) : 0)),
    y: Math.round(f.yTop + (refKg - p.kg) * pxPerKg),
  }));

  const last = pts[pts.length - 1];
  return {
    viewBox: f.viewBox,
    gridlines: f.gridlines ?? [],
    points: pts,
    firstValue: points[0]?.kg ?? null,
    lastValue: points[points.length - 1]?.kg ?? null,
    // A line needs two points: one weigh-in is a dot with its date, not a trend (design-pro, #95).
    path: pts.length > 1 ? `M${pts.map((p) => `${p.x} ${p.y}`).join(" L")}` : "",
    firstLabel: { x: f.x0, y: f.firstLabelY },
    lastLabel: last
      ? { x: last.x - 10, y: last.y + f.lastLabelDy }
      : { x: f.x1, y: f.emptyLabelY },
    dateLabelY: f.dateLabelY,
    dateLabelX: { start: f.x0, end: f.x1 },
  };
}

/**
 * The You board's target-lane dash, drawn the same on every surface — `stroke-dasharray` values in
 * SVG units, so web's emitter and the phone's `<Line>` read one constant rather than each carrying
 * "4 4" of their own.
 */
export const TARGET_LANE_DASH = "4 4";

/**
 * The lone weigh-in's entrance on the You board: one point is the whole chart — no line can be
 * drawn through it, so its dot stays (#95) and pops at `delayMs`, 0.9 s in on the board. Every
 * other chart draws the line alone (#1068). `you.css.ts` re-times the kit's `pd-0` to this; the
 * phone reads `delayMs` directly.
 */
export const WEIGHT_CHART_DOTS = { delayMs: 900 } as const;

/**
 * `withTargetLane` opens the You board's bottom lane: a dashed accent line in the band the taller
 * viewBox adds, its label above — DISPLAY, never the data scale (a 6 kg drop would sit off any
 * scale the three gridlines span). Off, the geometry is the board's plain one. The lane's VALUE
 * lives on its label, which the caller formats — the line means "the aim sits here".
 */
export function weightChart(points: readonly WeightPoint[], withTargetLane = false): {
  viewBox: string;
  gridlines: readonly number[];
  points: { x: number; y: number }[];
  path: string;
  /** The trend's first and last values — what the end labels name (#1114). Null when empty. */
  firstValue: number | null;
  lastValue: number | null;
  firstLabel: { x: number; y: number };
  lastLabel: { x: number; y: number };
  /** The y of the two date captions; their x's are the axis ends. */
  dateLabelY: number;
  dateLabelX: { start: number; end: number };
  /** The dashed target line, when one was asked for — you.html's lane at the band's bottom. */
  targetLine?: { x1: number; x2: number; y: number; dash: string };
  /** Where its "{w} · target" label sits, right-aligned just over the line. */
  targetLabel?: { x: number; y: number };
} {
  const g = weightLine(weightTrend(points), withTargetLane ? W_FRAME_LANE : W_FRAME);
  return withTargetLane ? {
    ...g,
    // The band the taller frame opens: the board's lane at y 104, its label above it. The value
    // lives on the label, not the axis — the line says "the aim sits here", never a scale reading.
    targetLine: { x1: 24, x2: 296, y: 104, dash: TARGET_LANE_DASH },
    targetLabel: { x: 296, y: 98 },
  } : g;
}

// ── The week's intake bars ────────────────────────────────────────────────────────────────────
//
// Progress's "This week" card: one bar a day against a dashed plan line, today picked out with a
// tint fill and an outline. The scale is the board's own — 1900 kcal of headroom over the baseline
// — and it yields to the data: past ~1.1× the largest figure on the card (plan or day), the px per
// kcal shrink so a 2,800-kcal plan and a 3,200-kcal day still fit the 142-tall viewBox. A bar over
// plan simply clears the dashed line and keeps going.

const BARS_BASE = 118;
/** The board's headroom: 100 px of bar for every 1,900 kcal. */
const BARS_BASELINE_FULL = 1900;

/**
 * The bars' one scale, shared by `weekBars` and `intakeChart`: `px` of bar for `full` kcal while
 * the data is quiet, yielding past `largest × 1.1` so a heavy week compresses instead of clipping.
 * Without `floor` a light week would stretch the bars to the frame and read as a record one.
 */
const barPxPerKcal = (px: number, floor: number, largest: number): number =>
  px / Math.max(floor, largest * 1.1);

export function weekBars(
  days: readonly (number | null)[],
  planKcal: number,
  todayIndex = -1,
): {
  viewBox: string;
  planLine: { x1: number; x2: number; y: number; dash: string };
  planLabel: { x: number; y: number };
  bars: ({ x: number; y: number; width: number; height: number; rx: number; tone: DayTone; today: boolean } | null)[];
  /** The day-letter captions, one per day whether it has a bar or not. */
  labels: { x: number; y: number }[];
} {
  const largest = Math.max(planKcal, ...days.map((d) => d ?? 0));
  const pxPerKcal = barPxPerKcal(100, BARS_BASELINE_FULL, largest);
  const planY = Math.round(BARS_BASE - planKcal * pxPerKcal);
  const bars = days.map((kcal, i) => {
    if (kcal === null) return null;
    const h = Math.round(kcal * pxPerKcal);
    return {
      x: 14 + i * 44,
      y: BARS_BASE - h,
      width: 26,
      height: h,
      rx: 4,
      tone: dayTone({ kcal, logged: true, when: i === todayIndex ? "today" : "past" }, planKcal),
      today: i === todayIndex,
    };
  });
  // The label hangs off the line's right end — but ABOVE any bar tall enough to reach into its
  // zone (the board's weekend is empty; a real Sunday bar can top right where "1,434" sits, #174).
  // At 12px a glyph is ~7px, so the label needs its own width of room back from x 312.
  const labelLeft = 312 - (String(Math.round(planKcal)).length + Math.floor((String(Math.round(planKcal)).length - 1) / 3)) * 7;
  let labelY = planY - 6;
  for (const b of bars) {
    if (b !== null && b.x + b.width > labelLeft) labelY = Math.min(labelY, b.y - 6);
  }
  return {
    viewBox: "0 0 320 142",
    planLine: { x1: 8, x2: 312, y: planY, dash: "3 3" },
    planLabel: { x: 312, y: labelY },
    bars,
    labels: days.map((_, i) => ({ x: 14 + i * 44 + 13, y: 136 })),
  };
}

// ── The goal progress bar ────────────────────────────────────────────────────────────────────
//
// Progress's goal card: `start → target` with the fill at the share already covered, "0.6 kg down"
// and "5.4 to go" beneath. Works in both directions — a gain goal's done/to-go run the other way.

export function goalBar(
  startKg: number,
  currentKg: number,
  targetKg: number,
): { share: number; doneKg: number; toGoKg: number } {
  const span = targetKg - startKg;
  if (span === 0) return { share: 1, doneKg: 0, toGoKg: 0 };
  const dir = Math.sign(span);
  const done = (currentKg - startKg) * dir;
  const toGo = (targetKg - currentKg) * dir;
  return {
    share: Math.round(clamp01(done / Math.abs(span)) * 1e4) / 1e4,
    doneKg: r1(Math.max(0, done)),
    toGoKg: r1(Math.max(0, toGo)),
  };
}

// ── The BMI bar ──────────────────────────────────────────────────────────────────────────────
//
// The last card on Progress: four neutral segments and a tick where the value lands
// (`product/design/pro/boards.py` `BMI_RANGES` / `_BPOS`). The SEGMENT bounds are the ones the
// labels print — "18.5–24.9" — while `scores.ts`'s `BMI_BANDS` derives its membership edges from
// this table, so a moved edge cannot strand a label.

/**
 * The four segments, in bar order: the id `bmiRange` returns, and the printed bounds the label
 * under it is built from. `lo`/`hi` are null on the open ends — "below 18.5" has no floor and
 * "30 and above" no ceiling; the tick borrows the inner neighbour's width there.
 */
export const BMI_SEGMENTS = [
  { id: "below-18.5", lo: null, hi: 18.5 },
  { id: "18.5-24.9", lo: 18.5, hi: 24.9 },
  { id: "25-29.9", lo: 25, hi: 29.9 },
  { id: "30-plus", lo: 30, hi: null },
] as const;

/**
 * Where the value's tick sits across the whole bar, 0..1 — `boards.py`'s `_BPOS`: the segment
 * index plus the value's fraction through its bounds, over four. An open segment borrows the
 * inner neighbour's width, so a 17 or a 34 pins inside its own segment rather than at its edge —
 * and clamped, so no value ever draws the tick outside the bar.
 */
export function bmiTick(value: number, range: string): number {
  const i = BMI_SEGMENTS.findIndex((s) => s.id === range);
  if (i < 0) return 0;
  const seg = BMI_SEGMENTS[i]!;
  const wLow = BMI_SEGMENTS[1]!.hi! - BMI_SEGMENTS[1]!.lo!;
  const wHigh = BMI_SEGMENTS[2]!.hi! - BMI_SEGMENTS[2]!.lo!;
  const lo = seg.lo ?? seg.hi! - wLow;
  const hi = seg.hi ?? seg.lo! + wHigh;
  return (i + clamp01((value - lo) / (hi - lo))) / BMI_SEGMENTS.length;
}

// ── Apple Health's intake bars ────────────────────────────────────────────────────────────────
//
// phone/health.html's "Intake · this week" card: a bar per bucket on a full-width baseline and a
// dashed ink line at the plan — `weekBars`' bigger sibling on its own frame. Two differences,
// both the board's: a day over plan stays accent rather than going `bad` (the card reads as a
// record, not a verdict), and the bucket count is the caller's — 7 days, 26 weeks, 12 months or
// however many years the window holds — so the pitch is derived, never fixed at seven.

const INTAKE = {
  /** The frame's width — the baseline, plan line and plan label all end at it. */
  frame: 350,
  viewBox: "0 0 350 150",
  /** The baseline every bar stands on. */
  base: 124,
  /** Pixels of bar for `max(plan, largest) × 1.1` — the headroom rule `weekBars` runs at 1900. */
  headroomPx: 114,
  /** The drawable width the bucket pitch divides — the frame less its 8 px margins. */
  inner: 334,
  /** The board's pitch at seven buckets: 48 px a slot, 30 px of bar, first bar at x 8. */
  pitchCap: 48,
  barCap: 30,
  barFill: 0.625, // 30 / 48
  labelY: 142,
} as const;

export function intakeChart(
  values: readonly (number | null)[],
  planKcal: number,
  todayIndex = -1,
): {
  viewBox: string;
  /** The frame's width — the baseline runs to it edge to edge. */
  frame: number;
  /** The y the bars stand on — a full-width hairline. */
  baseline: number;
  /** The dashed plan line, or null when the account has no plan to draw. */
  planLine: { x1: number; x2: number; y: number; dash: string } | null;
  planLabel: { x: number; y: number } | null;
  bars: ({ x: number; y: number; width: number; height: number; rx: number; today: boolean } | null)[];
  /** One caption per bucket, centred on the slot — a bucket with no bar still names itself. */
  labels: { x: number; y: number }[];
} {
  const n = values.length;
  const pitch = Math.min(INTAKE.pitchCap, Math.round(INTAKE.inner / Math.max(1, n)));
  const width = Math.min(INTAKE.barCap, Math.round(pitch * INTAKE.barFill));
  const largest = Math.max(planKcal, ...values.map((v) => v ?? 0));
  const pxPerKcal = barPxPerKcal(INTAKE.headroomPx, BARS_BASELINE_FULL, largest);
  const planY = Math.round(INTAKE.base - planKcal * pxPerKcal);
  return {
    viewBox: INTAKE.viewBox,
    frame: INTAKE.frame,
    baseline: INTAKE.base,
    planLine: planKcal > 0 ? { x1: 0, x2: INTAKE.frame, y: planY, dash: "5 4" } : null,
    planLabel: planKcal > 0 ? { x: INTAKE.frame, y: planY - 6 } : null,
    bars: values.map((v, i) => {
      if (v === null) return null;
      const h = Math.round(v * pxPerKcal);
      return { x: 8 + i * pitch, y: INTAKE.base - h, width, height: h, rx: 3, today: i === todayIndex };
    }),
    labels: values.map((_, i) => ({ x: 8 + i * pitch + Math.round(width / 2), y: INTAKE.labelY })),
  };
}

// ── The compare chart: bars against a line on two axes ────────────────────────────────────────
//
// phone/health-compare.html: intake-shaped bars on the left axis, a second series as an ink line
// with hollow dots on the right, three hairlines, bucket captions under the slots. A gap on
// either side is drawn, not smoothed — a null on the bars side is an empty slot, on the line side
// a break in the run, for the same reason `trend.ts` keeps null apart from zero.

const CMP = {
  /** The frame's width — the plot sits between the two measured gutters inside it. */
  frame: 350,
  viewBox: "0 0 350 164",
  top: 10,
  plotBottom: 140,
  /** The floor for the derived gutters — wider axis words widen them, never clip them. */
  gutter: 44,
  labelGap: 6,
  font: 12,
  barCap: 20,
  barFill: 0.55,
  xLabelY: 160,
} as const;

interface CmpScale { lo: number; hi: number; ticks: number[] }

/**
 * One axis with round ends. Bars floor at zero — a bar is a quantity — and a floating series
 * rounds its own extremes out to the step, so the value at the end is never ON the frame.
 * Only a flat series is padded (without it the rounding collapses to a line at its own edge).
 */
function cmpScale(values: readonly (number | null)[], kind: "bar" | "line"): CmpScale | null {
  const known = values.flatMap((v) => (v === null ? [] : [v]));
  if (known.length === 0) return null;
  let lo = kind === "bar" ? 0 : Math.min(...known);
  let hi = Math.max(...known);
  if (lo === hi) {
    const pad = (Math.abs(hi) || 1) * 0.15;
    lo -= pad;
    hi += pad;
  }
  const raw = (hi - lo) / 2;
  const mag = 10 ** Math.floor(Math.log10(raw));
  const step = [1, 2, 5, 10].map((m) => m * mag).find((s) => s >= raw)!;
  lo = kind === "bar" ? 0 : Math.floor(lo / step) * step;
  hi = Math.ceil(hi / step) * step;
  return { lo, hi, ticks: [lo, (lo + hi) / 2, hi] };
}

/** One gutter, measured from the labels that go in it — see `chart.tsx`'s `axisPad` for why. */
function cmpGutter(labels: readonly string[]): number {
  const widest = labels.reduce((w, l) => Math.max(w, l.length), 0);
  const need = Math.ceil(widest * CMP.font * 0.62) + CMP.labelGap;
  return Math.min(Math.max(need, CMP.gutter), Math.floor(CMP.frame / 3));
}

export function compareChart(
  bars: readonly (number | null)[],
  line: readonly (number | null)[],
  labels: readonly string[],
  formatBars: (v: number) => string,
  formatLine: (v: number) => string,
): {
  viewBox: string;
  plotLeft: number;
  plotWidth: number;
  /** The y's of the three hairlines — the bars axis' lo, mid and hi. */
  gridlines: number[];
  leftLabels: { x: number; y: number; text: string }[];
  rightLabels: { x: number; y: number; text: string }[];
  bars: ({ x: number; y: number; width: number; height: number; rx: number } | null)[];
  /** One path per run of consecutive known line points — a gap is a break, not a bridge. */
  runs: string[];
  /** A hollow dot per known line point; the caller gives it the surface fill and ink stroke. */
  dots: { x: number; y: number; r: number }[];
  labels: { x: number; y: number; text: string }[];
} {
  const plotH = CMP.plotBottom - CMP.top;
  const a = cmpScale(bars, "bar");
  const b = cmpScale(line, "line");
  const left = cmpGutter((a?.ticks ?? []).map(formatBars));
  const right = b ? cmpGutter(b.ticks.map(formatLine)) : CMP.labelGap;
  const plotW = CMP.frame - left - right;
  const n = Math.max(bars.length, line.length, labels.length);
  const slot = n > 0 ? plotW / n : 0;
  const xOf = (i: number) => left + slot * (i + 0.5);
  const yOf = (sc: CmpScale, v: number) => CMP.top + plotH - ((v - sc.lo) / (sc.hi - sc.lo)) * plotH;
  const barW = Math.min(CMP.barCap, slot * CMP.barFill);

  const runs: string[] = [];
  let run: { x: number; y: number }[] = [];
  line.forEach((v, i) => {
    if (v === null || b === null) {
      if (run.length) runs.push(run.map((p, j) => `${j === 0 ? "M" : "L"}${p.x} ${p.y}`).join(" "));
      run = [];
    } else run.push({ x: xOf(i), y: Math.round(yOf(b, v) * 10) / 10 });
  });
  if (run.length) runs.push(run.map((p, j) => `${j === 0 ? "M" : "L"}${p.x} ${p.y}`).join(" "));

  return {
    viewBox: CMP.viewBox,
    plotLeft: left,
    plotWidth: plotW,
    gridlines: (a?.ticks ?? []).map((t) => Math.round(yOf(a!, t))),
    leftLabels: (a?.ticks ?? []).map((t) => ({ x: left - CMP.labelGap, y: Math.round(yOf(a!, t)) + 4, text: formatBars(t) })),
    rightLabels: (b?.ticks ?? []).map((t) => ({ x: left + plotW + CMP.labelGap, y: Math.round(yOf(b!, t)) + 4, text: formatLine(t) })),
    bars: bars.map((v, i) => {
      if (v === null || a === null) return null;
      // The height comes from the ROUNDED top, not the other way: y + height is exactly the
      // baseline this way, where two independent roundings drifted a half pixel off it.
      const y = Math.round(yOf(a, v) * 10) / 10;
      return {
        x: Math.round((xOf(i) - barW / 2) * 10) / 10,
        y,
        width: Math.round(barW * 10) / 10,
        height: Math.max(0, CMP.plotBottom - y),
        rx: 3,
      };
    }),
    runs,
    dots: line.flatMap((v, i) => (v === null || b === null ? [] : [{ x: xOf(i), y: Math.round(yOf(b, v) * 10) / 10, r: 3.5 }])),
    labels: labels.map((text, i) => ({ x: Math.round(xOf(i) * 10) / 10, y: CMP.xLabelY, text })),
  };
}

// ── The Body screen's weigh-in line ───────────────────────────────────────────────────────────
//
// phone/health-body.html: the same logged-weights line as Progress's card on a wider frame —
// 340×130 with no hairlines, the first and last values named, the date range under. Same mapping
// as `weightChart` (`weightLine`), a different `WeightFrame` — the frame is the whole difference,
// and the same trend: the Body screen's line is `weightTrend` too, because the two surfaces
// cannot disagree about where the weight is going (#1114 — the scribbles were reported HERE).

export function bodyWeightChart(points: readonly WeightPoint[]): {
  viewBox: string;
  gridlines: readonly number[];
  points: { x: number; y: number }[];
  path: string;
  /** The trend's first and last values — what the end labels name (#1114). Null when empty. */
  firstValue: number | null;
  lastValue: number | null;
  firstLabel: { x: number; y: number };
  lastLabel: { x: number; y: number };
  dateLabelY: number;
  dateLabelX: { start: number; end: number };
} {
  return weightLine(weightTrend(points), BW_FRAME);
}
